---
output:
  word_document: default
  pdf_document: default
  html_document: default
---

#Set the number of simulations
```{r}
num_simulations = 10000
```

This is assigned to count the number of times the bus is empty after running the simulations n(assigned) number of times
```{r}
count = 0

```

#No of stops
```{r}
stops = 10
```

#We simulate for each stop and all the given conditions that is 
```{r}
for (i in 1:num_simulations) {
  passengers_on_bus <- 0
  
  for (stop in 1:stops) {
    #check for condition 1, that is, likely to get on the bus independent of others with a 20% chance
    passengers_alighting = sum(sample(c(0, 1), passengers_on_bus, replace = TRUE, prob = c(0.8, 0.2)))
    passengers_on_bus = passengers_on_bus - passengers_alighting 
    
    #check for condition 2, that is, there is a 50%/40%/10% chance of 0/1/2 passengers getting on board
    passengers_boarding <- sum(sample(0:2, 1, replace = TRUE, prob = c(0.5, 0.4, 0.1)))
    passengers_on_bus = passengers_on_bus + passengers_boarding
    
    # Ensure the number of passengers on the bus doesn't go negative
    passengers_on_bus = max(0, passengers_on_bus)
  }
  # Check if the bus is empty after the 10th stop and increment count if true
  if (passengers_on_bus == 0) 
    count = count +1
}
```

#Check if the bus is empty after the 10th stop. If it is empty we increment count by 1
```{r}
count
```

#Calculate the probability
```{r}
prob_empty = count / num_simulations
(prob_empty)
```

```{r}

  
    

```


